const projectTemplate = {
  fields: [
    'dcp_name',
    'dcp_projectid',
    'dcp_projectname',
    'dcp_projectbrief',
    'dcp_borough',
    'dcp_communitydistricts',
    'dcp_ulurp_nonulurp',
    'dcp_leaddivision',
    'dcp_ceqrtype',
    'dcp_ceqrnumber',
    'dcp_easeis',
    'dcp_leadagencyforenvreview',
    'dcp_alterationmapnumber',
    'dcp_sisubdivion',
    'dcp_sischoolseat',
    'dcp_previousactiononsite',
    'dcp_wrpnumber',
    'dcp_nydospermitnumber',
    'dcp_bsanumber',
    'dcp_lpcnumber',
    'dcp_decpermitnumber',
    'dcp_femafloodzonea',
    'dcp_femafloodzonecoastala',
    'dcp_femafloodzonev',
    'dcp_publicstatus_simp',
    'keywords',
    'bbls',
    'bbl_multipolygon',
    'bbl_featurecollection',
  ],
  entities: ['actions', 'milestones', 'addresses', 'applicantteam'],
  entity_fields: {
    actions: [
      'dcp_name',
      'actioncode',
      'dcp_ulurpnumber',
      'dcp_prefix',
      'dcp_ccresolutionnumber',
      'dcp_zoningresolution',
    ],
    milestones: [
      'dcp_name',
      'milestonename',
      'dcp_plannedstartdate',
      'dcp_plannedcompletiondate',
      'dcp_actualstartdate',
      'dcp_actualenddate',
      'statuscode',
      'outcome',
      'zap_id',
      'dcp_milstonesequence',
      'display_sequence',
      'display_name',
      'display_date',
      'display_date_2',
      'display_description',
    ],
    addresses: [
      'dcp_validatedaddressnumber',
      'dcp_validatedstreet',
    ],
    applicantteam: [
      'role',
      'name',
    ],
  },
};

module.exports = projectTemplate;
