/* eslint-disable indent */

const {
  VISIBILITY,
  STATUSCODE,
  STATECODE,
  APPLICANTROLE,
} = require('../../constants');

const { escapeFetchParam } = require('./helpers');

/**
 * Returns FetchXML query param for fetching a single project for the `/project/id` route
 */
function projectXML(projectId) {
  return [
    `<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">`,
      `<entity name="dcp_project">`,
        `<attribute name="dcp_name"/>`,
        `<attribute name="dcp_projectid"/>`,
        `<attribute name="dcp_projectname"/>`,
        `<attribute name="dcp_projectbrief"/>`,
        `<attribute name="dcp_borough"/>`,
        `<attribute name="dcp_communitydistricts"/>`,
        `<attribute name="dcp_ulurp_nonulurp"/>`,
        `<attribute name="dcp_ceqrtype"/>`,
        `<attribute name="dcp_ceqrnumber"/>`,
        `<attribute name="dcp_femafloodzonea"/>`,
        `<attribute name="dcp_femafloodzonecoastala"/>`,
        `<attribute name="dcp_femafloodzonev"/>`,
        `<attribute name="dcp_publicstatus"/>`,
        `<attribute name="dcp_currentmilestone"/>`,
        `<filter type="and">`,
          `<condition attribute="dcp_name" operator="eq" value="${escapeFetchParam(projectId)}" />`,
          `<condition attribute="dcp_visibility" operator="eq" value="${VISIBILITY.GENERAL_PUBLIC}" />`,
        `</filter>`,
        `<link-entity name="dcp_projectbbl" from="dcp_project" to="dcp_projectid" link-type="outer" alias="bbls">`,
          `<attribute name="dcp_bblnumber" />`,
          `<filter type="and">`,
            `<condition attribute="dcp_bblnumber" operator="not-null" />`,
            `<condition attribute="statuscode" operator="eq" value="1"/>`,
          `</filter>`,
        `</link-entity>`,
        `<link-entity name="dcp_projectaction" from="dcp_project" to="dcp_projectid" link-type="outer" alias="actions">`,
          `<attribute name="dcp_name" />`,
          `<attribute name="dcp_ulurpnumber" />`,
          `<attribute name="statuscode" />`,
          `<filter type="and">`,
            `<condition attribute="statuscode" operator="ne" value="${STATUSCODE.MISTAKE}" />`,
          `</filter>`,
        `</link-entity>`,
        `<link-entity name="dcp_projectmilestone" from="dcp_project" to="dcp_projectid" link-type="outer" alias="milestones">`,
          `<order attribute="dcp_sequence" descending="false" />`,
          `<attribute name="dcp_name" />`,
          `<attribute name="dcp_milestone" />`,
          `<attribute name="dcp_plannedstartdate" />`,
          `<attribute name="dcp_plannedcompletiondate" />`,
          `<attribute name="dcp_actualstartdate" />`,
          `<attribute name="dcp_actualenddate" />`,
          `<filter>`,
            `<condition attribute="statuscode" operator="ne" value="${STATUSCODE.OVERRIDDEN}" />`,
          `</filter>`,
        `</link-entity>`,
        `<link-entity name="dcp_projectkeywords" from="dcp_project" to="dcp_projectid" link-type="outer" alias="keywords">`,
          `<attribute name="dcp_keyword" />`,
          `<filter type="and">`,
            `<condition attribute="statecode" operator="eq" value="${STATECODE.ACTIVE}" />`,
          `</filter>`,
        `</link-entity>`,
        `<link-entity name="dcp_projectapplicant" from="dcp_project" to="dcp_projectid" link-type="outer" alias="applicants">`,
          `<attribute name="dcp_applicantrole"/>`,
          `<attribute name="dcp_applicant_customer"/>`,
          `<filter type="or">`,
            `<condition attribute="dcp_applicantrole" operator="eq" value="${APPLICANTROLE.APPLICANT}" />`,
            `<condition attribute="dcp_applicantrole" operator="eq" value="${APPLICANTROLE.COAPPLICANT}" />`,
          `</filter>`,
          `<filter type="and">`,
            `<condition attribute="statecode" operator="eq" value="0"/>`,
          `</filter>`,
        `</link-entity>`,
        `<link-entity name="dcp_projectaddress" from="dcp_project" to="dcp_projectid" link-type="outer" alias="addresses">`,
          `<attribute name="dcp_validatedaddressnumber" />`,
          `<attribute name="dcp_validatedstreet" />`,
          `<filter type="and">`,
            `<condition attribute="dcp_validatedaddressnumber" operator="not-null" />`,
            `<condition attribute="dcp_validatedstreet" operator="not-null" />`,
            `<condition attribute="statuscode" operator="eq" value="1"/>`,
          `</filter>`,
        `</link-entity>`,
      `</entity>`,
    `</fetch>`,
  ].join('');
}

module.exports = {
  projectXML,
};
