module.exports = [
  `<attribute name="dcp_name" />`,
  `<attribute name="statuscode" />`,
  `<attribute name="dcp_projectname" />`,
  `<attribute name="dcp_borough" />`,
  `<attribute name="dcp_certificationtargetdate" />`,
  `<attribute name="dcp_ulurp_nonulurp" />`,
  `<attribute name="dcp_leadplanner" />`,
  `<attribute name="dcp_leadaction" />`,
  `<attribute name="dcp_currentmilestone" />`,
  `<attribute name="dcp_projectid" />`,
  `<link-entity name="dcp_projectapplicant" from="dcp_project" to="dcp_projectid" link-type="outer" alias="applicants">`,
    `<attribute name="dcp_applicantrole"/>`,
    `<attribute name="dcp_applicant_customer"/>`,
  `</link-entity>`,
  `<order descending="false" attribute="dcp_name" />`,
];
